targetInstance: ${TEST_URL:http://rd-user-profile-api-preview.service.core-compute-preview.internal}
spring.flyway.enabled: false

idam.api.url: ${IDAM_API_URL:https://idam-api.preview.platform.hmcts.net}
up.api.url: ${UP_API_URL:http://rd-user-profile-api-preview.service.core-compute-preview.internal}
generated.user.email.pattern: ${GENERATED_USER_EMAIL_PATTERN:freg-test-user-%s@feemail.com}
test.url: ${TEST_URL:http://rd-user-profile-api-preview.service.core-compute-preview.internal}
test.user.password: ${TEST_USER_PASSWORD:Hmcts123}

s2s.auth.secret: ${S2S_SECRET:OLMEJQA7UHU6EZKG}
s2s.auth.url: ${S2S_URL_TO_TEST:http://rpe-service-auth-provider-aat.service.core-compute-aat.internal}

idam.auth.tokenAuth: ${IDAM_TOKEN_ATUH:cmQtcHJvZmVzc2lvbmFsLWFwaTpjYzVmMmE2LTk2OTAtMTFlOS1iYzQyLTUyNmFmNzc2NGY2NA==}
idam.auth.redirectUrl: ${IDAM_REDIRECT_URL:https://rd-professional-api-preview.service.core-compute-preview.internal/oauth2redirect}