version: '2.1'

services:

  rd-profile-sync-db:
    build:
      context: database
    image: hmcts/rd-profile-sync-db
    container_name: rd-profile-sync-db
    volumes:
      - rd-profile-sync-db-volume:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD="${POSTGRES_PASSWORD:-dbsyncdata}"
    ports:
      - 5428:5432

volumes:
  rd-profile-sync-db-volume:
