java:
  image: ${IMAGE_NAME}
  ingressHost: ${SERVICE_FQDN}
  environment:
    POSTGRES_NAME: "{{ .Values.postgresql.auth.database}}"
    POSTGRES_USERNAME: "{{ .Values.postgresql.auth.username}}"
    POSTGRES_PASSWORD: "{{ .Values.postgresql.auth.password}}"
    POSTGRES_CONNECTION_OPTIONS:
  postgresql:
    enabled: true
    auth:
      username: dbsyncdata
      password: dbsyncdata
      database: dbsyncdata
  keyVaults:
    rd:
      secrets:
        - name: profile-sync-s2s-secret
          alias: S2S_SECRET
        - name: OAUTH2-AUTH
          alias: idam.api.authorization
        - name: ApplicationInsightsInstrumentationKey
          alias: azure.application-insights.instrumentation-key
